### ISSUE TITLE
Vastly different behaviour if default values are explicitly stated.

### ISSUE THREAD

**Issue by mjsir911** [indexdata/yaz#47]
If I set `sru` to `soap`, which is the documented default value, all requests return XML.

Simple code:
```c
#include <stdio.h>
#include <yaz/zoom.h>

int main(int argc, char *argv[]) {
	int err;
	ZOOM_options opt = ZOOM_options_create();
	ZOOM_options_set(opt, "sru", argv[1]); // uncomment for no error
	ZOOM_options_set(opt, "databaseName", "voyager"); // uncomment for no error
	ZOOM_connection conn = ZOOM_connection_create(opt);
	ZOOM_connection_connect(conn, "z3950.loc.gov", 7090);

	if ((err = ZOOM_connection_errcode(conn))) {
		printf("error!");
		exit(err);
	}

	ZOOM_query q = ZOOM_query_create();
	ZOOM_query_prefix(q, "@attr 1=7 9780596007126");

	ZOOM_resultset ress = ZOOM_connection_search(conn, q);
	if ((err = ZOOM_connection_errcode(conn))) {
		printf("error!");
		exit(err);
	}

	if (ZOOM_resultset_size(ress) < 1) {
		printf("Resultset empty!");
	}

	ZOOM_record record = ZOOM_record_clone(ZOOM_resultset_record(ress, 0));

	int len;
	printf("%s\n", ZOOM_record_get(record, "render; charset=marc8,iso-8859-1", &len));
}
```

if the file is called with a null argument (which just falls back to default implementation) like so `./test ""`, it returns with a MARC-ish representation.

If the file is called with the argument `"soap"` (which is the documented default value) with `./test "soap"`, it returns XML.

This is further explorations into issue #46

**Comment by adamdickmeiss** [comment]
Vasty different behavior because when you specify a host WITHOUT http:// YAZ will operates as a Z39.50 client. If you do specify sru (but not http), it will turn to HTTP mode. 

If you do specify http:// as part of the host name, the default operation is sru=soap (which is what the documentation says).

We'll make a note about this behavior in the documentation (the case where http:// is omitted).
