### ISSUE TITLE
yaz-config file not installed from Ubuntu repository?

### ISSUE THREAD

**Issue by vfscalfani** [indexdata/yaz#82]
Hello, 

On Ubuntu 22.04 LTS, after installing yaz and development files via:

```
sudo apt-get install yaz libyaz-dev yaz-doc
```
I am not seeing a yaz-config file in `/usr/bin/`, however if I also install the `libyazpp-dev` package, a yazpp-config file is indeed added to `/usr/bin/`

So, I'm not sure if there should also be a separate yaz-config file for C? If so, is the easiest resolution to simply create my own yaz-config file and add it to `usr/bin`?  Is there a way to run `./configure` with a yaz installation from repositories?

Thanks very much for any help. 

Vin

**Comment by MikeTaylor** [comment]
Hi, @vfscalfani. Yes, the Debian packaging people took a decision — rather an arrogant one, IMHO — to remove `yaz-config` from their packages, on the basis that people should be using `pkg-config` instead.

Because I needed to get some actual work done, I made a polyfill for `yaz-config`, which you can find at https://github.com/MikeTaylor/yaz-config-polyfill — I hope it helps.

IIRC, @adamdickmeiss had a better plan to resolve this, but I can't remember what it was.

**Comment by adamdickmeiss** [comment]
If you are using Index Data's you also just install libyaz5-dev (rather than libyaz-dev). This yaz-config. This, however, probably also requires you to choose libyaz5 from Index Data repo.

**Comment by vfscalfani** [comment]
Thanks so much for both of these solutions!
